format = """\
$character\
$directory\
$git_branch\
${custom.git_dirty}\
"""

add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
format = '[$path](bold cyan) '
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = '[git:\(](bold blue)[$branch](red)[\)](bold blue) '
symbol = ''

[git_status]
disabled = true

[custom.git_dirty]
command = 'echo "✗"'
when = '[ -n "$(git status --porcelain 2>/dev/null)" ]'
format = '[$output](yellow) '
require_repo = true
